=== HilscherAutomation/meta-hilscher-netfield/documentation/implementations/oem/device-data/device-data.schema.json
{
  "definitions": {
    "proxy": {
      "type": "object",
      "required": [
        "host"
      ],
      "properties": {
        "host": {
          "type": "string",
          "examples": [
            "<ip>:<port>"
          ],
          "pattern": "^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!\\:[0-9]{1,5}$)|\\:[0-9]{1,5}$)){4}"
        },
        "username": {
          "type": "string",
          "pattern": "^.*$"
        },
        "password": {
          "type": "string",
          "pattern": "^.*$"
        }
      }
    },
    "cidr": {
      "type": "string",
      "examples": [
        "192.168.1.1/24"
      ],
      "pattern": "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))$"
    },
    "ipv4": {
      "type": "string",
      "pattern": "^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$"
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://www.hilscher.com/netfield-device-label.json",
  "title": "netFIELDOS Device Label",
  "type": "object",
  "required": [
    "version",
    "product_name",
    "serial_number",
    "product_number",
    "date_code",
    "processor_serial_number",
    "mac"
  ],
  "properties": {
    "version": {
      "type": "string",
      "default": "2",
      "pattern": "^[0-9]+$"
    },
    "product_name": {
      "type": "string",
      "pattern": "^.*$"
    },
    "serial_number": {
      "type": "string",
      "pattern": "^.*$"
    },
    "product_number": {
      "type": "string",
      "pattern": "^.*$"
    },
    "date_code": {
      "type": "string",
      "pattern": "^.*$"
    },
    "processor_serial_number": {
      "type": "string",
      "pattern": "^[0-9A-F]+$"
    },
    "mac": {
      "title": "MAC address of eth0",
      "type": "string",
      "pattern": "^[0-9A-F]{12}$"
    },
    "cifx": {
      "type": "object",
      "required": [
        "device_number",
        "serial_number",
        "revision_number",
        "mac",
        "date_code"
      ],
      "properties": {
        "device_number": {
          "type": "string",
          "pattern": "^[0-9]+$"
        },
        "serial_number": {
          "type": "string",
          "pattern": "^[0-9]+$"
        },
        "revision_number": {
          "type": "string",
          "pattern": "^[0-9A-F]+$"
        },
        "mac": {
          "type": "string",
          "pattern": "^[0-9A-F]{12}$"
        },
        "date_code": {
          "type": "string",
          "pattern": "^.*$"
        }
      }
    },
    "wifi": {
      "type": "object",
      "required": [
        "mac"
      ],
      "properties": {
        "mac": {
          "type": "string",
          "pattern": "^0|[0-9A-F]{12}$"
        }
      }
    },
    "bluetooth": {
      "type": "object",
      "required": [
        "mac"
      ],
      "properties": {
        "mac": {
          "type": "string",
          "pattern": "^0|[0-9A-F]{12}$"
        }
      }
    },
    "oem_data": {
      "type": "object",
      "required": [],
      "properties": {
        "identification": {
          "type": "object",
          "required": [],
          "properties": {
            "variant": {
              "type": "string",
              "pattern": "^.*$"
            },
            "product_number": {
              "type": "string",
              "pattern": "^.*$"
            },
            "serial_number": {
              "type": "string",
              "pattern": "^.*$"
            },
            "product_name": {
              "type": "string",
              "pattern": "^.*$"
            },
            "equipment_id": {
              "type": "string",
              "pattern": "^[0-9A-F]{12}$"
            }
          }
        },
        "iotedge": {
          "type": "object",
          "required": [
            "method"
          ],
          "properties": {
            "method": {
              "enum": [
                "symmetric_key",
                "tpm",
                "x509"
              ]
            },
            "global_endpoint": {
              "type": "string",
              "pattern": "^.*$"
            },
            "scope_id": {
              "type": "string",
              "pattern": "^.*$"
            },
            "registration_id": {
              "type": "string",
              "pattern": "^.*$"
            },
            "device_crt": {
              "type": "string",
              "pattern": "^.*$",
              "description": "Base64 encoded X.509 certificate. Must include Root/Intermediate CA certificates."
            },
            "device_key": {
              "type": "string",
              "pattern": "^.*$",
              "description": "Base64 encoded private key."
            },
            "device_key_uri": {
              "type": "string",
              "pattern": "^.*$",
              "description": "PKCS11 uri for iotedge."
            },
            "pkcs11_db": {
              "type": "string",
              "pattern": "^.*$",
              "description": "Compressed PKCS11 database for TPM onboarding."
            },
            "tpm_so_pin": {
              "type": "string",
              "pattern": "^.*$",
              "description": "SO pin for TPM token that holds device_key_uri."
            },
            "tpm": {
              "type": "object",
              "required": [],
              "properties": {
                "device": {
                  "type": "string",
                  "default": "device:/dev/tpmrm0"
                },
                "owner_auth": {
                  "type": "string",
                  "default": ""
                },
                "endorsement_auth": {
                  "type": "string",
                  "default": ""
                }
              }
            }
          }
        },
        "branding": {
          "type": "object",
          "required": [
            "version"
          ],
          "properties": {
            "version": {
              "type": "string",
              "default": "1.0.0",
              "pattern": "^.*$"
            },
            "deviceManager": {
              "type": "object",
              "required": [],
              "properties": {
                "enabledPlugins": {
                  "type": "array",
                  "uniqueItems": true,
                  "default": [],
                  "items": {
                    "type": "string",
                    "pattern": "^.*$"
                  }
                },
                "disabledPlugins": {
                  "type": "array",
                  "uniqueItems": true,
                  "default": [],
                  "items": {
                    "type": "string",
                    "pattern": "^.*$"
                  }
                },
                "remoteAccess": {
                  "type": "string",
                  "default": "off",
                  "oneOf": [
                    {
                      "pattern": "^(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2})\\:(\\d{2})\\:(\\d{2})[+-](\\d{2})\\:(\\d{2})$"
                    },
                    {
                      "enum": [
                        "on",
                        "off"
                      ]
                    }
                  ]
                }
              }
            },
            "services": {
              "type": "object",
              "required": [],
              "properties": {
                "deviceManager": {
                  "type": "object",
                  "required": [],
                  "properties": {
                    "httpsPort": {
                      "type": "integer",
                      "default": 443
                    },
                    "httpPort": {
                      "type": "integer",
                      "default": 80
                    }
                  }
                },
                "ssh": {
                  "type": "object",
                  "required": [],
                  "properties": {
                    "enabled": {
                      "type": "boolean",
                      "default": true
                    },
                    "port": {
                      "type": "integer",
                      "default": 22
                    }
                  }
                },
                "docker": {
                  "type": "object",
                  "required": [],
                  "properties": {
                    "enabled": {
                      "type": "boolean",
                      "default": true
                    },
                    "dns": {
                      "type": "array",
                      "uniqueItems": true,
                      "default": [],
                      "items":{ "$ref": "#/definitions/ipv4" }
                    }
                  }
                }
              }
            },
            "ntp": {
              "type": "object",
              "required": [],
              "properties": {
                "enabled": {
                  "type": "boolean",
                  "default": true
                },
                "timezone": {
                  "type": "string",
                  "default": "UTC",
                  "pattern": "^.*$"
                },
                "servers": {
                  "type": "array",
                  "uniqueItems": true,
                  "default": [],
                  "items": {
                    "type": "string",
                    "default": "",
                    "pattern": "^.*$"
                  }
                }
              }
            },
            "interfaces": {
              "type": "array",
              "uniqueItems": true,
              "default": [],
              "items": {
                "type": "object",
                "required": [
                  "name",
                  "mode"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "default": "eth0",
                    "pattern": "^.*$"
                  },
                  "mode": {
                    "enum": [
                      "auto",
                      "manual",
                      "disabled"
                    ]
                  },
                  "address": {
                    "$ref": "#/definitions/cidr"
                  },
                  "dns": {
                    "type": "array",
                    "uniqueItems": true,
                    "default": [],
                    "items": {
                      "$ref": "#/definitions/ipv4"
                    }
                  },
                  "gateway": {
                    "$ref": "#/definitions/ipv4"
                  },
                  "metric": {
                    "type": "integer"
                  },
                  "routes": {
                    "type": "array",
                    "uniqueItems": true,
                    "default": [],
                    "items": {
                      "type": "object",
                      "required": [
                        "address",
                        "gateway"
                      ],
                      "properties": {
                        "address": {
                          "$ref": "#/definitions/cidr"
                        },
                        "gateway": {
                          "$ref": "#/definitions/ipv4"
                        },
                        "metric": {
                          "type": "integer",
                          "default": 1000,
                          "minimum": 0,
                          "maximum": 1000
                        }
                      }
                    }
                  }
                }
              }
            },
            "proxy": {
              "type": "object",
              "properties": {
                "http": {
                  "$ref": "#/definitions/proxy"
                },
                "https": {
                  "$ref": "#/definitions/proxy"
                },
                "ftp": {
                  "$ref": "#/definitions/proxy"
                }
              }
            },
            "netFieldCloud": {
              "type": "object",
              "required": [
                "defaultMode",
                "modeOptions"
              ],
              "properties": {
                "defaultMode": {
                  "type": "integer",
                  "default": 0
                },
                "modeOptions": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "default": [],
                  "items": {
                    "enum": [
                      "manual",
                      "advanced",
                      "zeroTouch"
                    ]
                  }
                },
                "defaultInstance": {
                  "type": "integer",
                  "default": 0
                },
                "instanceOptions": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "default": [],
                  "items": {
                    "type": "object",
                    "required": [
                      "name",
                      "host"
                    ],
                    "properties": {
                      "name": {
                        "type": "string",
                        "pattern": "^.*$"
                      },
                      "host": {
                        "type": "string",
                        "examples": [
                          "api.netfield.io"
                        ],
                        "pattern": "^.*$"
                      }
                    }
                  }
                },
                "upstreamProtocol": {
                  "enum": [
                    "AMQP",
                    "MQTT",
                    "AMQPWS",
                    "MQTTWS"
                  ],
                  "default": "AMQP"
                }
              }
            },
            "users": {
              "type": "array",
              "uniqueItems": true,
              "default": [],
              "items": {
                "type": "object",
                "required": [
                  "name",
                  "mode"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "title": "Linux username",
                    "pattern": "^[a-z_][a-z0-9_-]{0,31}$"
                  },
                  "mode": {
                    "enum": [
                      "add",
                      "change",
                      "delete"
                    ],
                    "default": "add"
                  },
                  "shell": {
                    "enum": [
                      "/bin/sh",
                      "/bin/zsh",
                      "/bin/bash",
                      "/sbin/nologin"
                    ],
                    "default": "/bin/sh"
                  },
                  "group": {
                    "type": "string",
                    "title": "Linux main usergroup",
                    "pattern": "^[a-z_][a-z0-9_-]{0,31}$"
                  },
                  "home": {
                    "type": "string",
                    "title": "Linux home directory",
                    "pattern": "^.*$"
                  },
                  "password": {
                    "type": "string",
                    "title": "Linux hashed password",
                    "description": "Generated via 'echo <password> | openssl passwd -6 -stdin",
                    "pattern": "^.*$",
                    "examples": [
                      "$6$tsTQ1XOmu23ctGtt$SFRKDyuVl01Hnls.oCripu5zXLrNJ1ZbkJ1s2NAJrEf6n7F099OWbVOfSIqUubSqeME1J9P8taJ/MM8zM3hDB0"
                    ]
                  },
                  "forcePasswordChange": {
                    "type": "boolean",
                    "description": "Force password change on first login",
                    "default": false
                  },
                  "additionalGroups": {
                    "type": "array",
                    "items": {
                      "title": "Linux user groups",
                      "type": "string",
                      "pattern": "^[a-z_][a-z0-9_-]{0,31}$",
                      "examples": [
                        "sudo",
                        "docker"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== HilscherAutomation/meta-hilscher-netfield/documentation/implementations/oem/device-data/device-data.json
{
        "version": "2",
        "product_name": "NIOT-E-NFL90-Q2N16-N",
        "serial_number": "20000",
        "product_number": "1320400",
        "date_code": "2020-12-16 13:00:49",
        "processor_serial_number": "0000000000020038",
        "mac": "0001C027D5DB",
        "cifx": {
                "device_number": "7690103",
                "serial_number": "23276",
                "revision_number": "4",
                "mac": "0002A260B8D4",
                "date_code": "5160"
        },
        "wifi": {
                "mac": "0"
        },
        "bluetooth": {
                "mac": "0"
        },
        "oem_data": {
        "identification": {
            "variant": "EVAL",
            "product_number": "",
            "serial_number": "",
            "product_name": "sensorEDGE",
            "equipment_id": "6175F2CE5A80"
        },
        "iotedge": {
            "method": "symmetric_key",
            "registration_id": "12345678",
            "scope_id": "12345678",
            "symmetric_key": "12345678"
        },
        "branding": {
            "version": "1.0.0",
            "deviceManager": {
                "enabledPlugins": ["plugin-name-a"],
                "disabledPlugins": ["plugin-name-b"],
                "remoteAccess": "on"
            },
            "services": {
                "deviceManager": {
                    "httpsPort": 443,
                    "httpPort": 80
                },
                "ssh": {
                    "enabled": true,
                    "port": 22
                },
                "docker": {
                    "enabled": false
                }
            },
            "ntp" : {
                "enabled": true,
                "timezone": "UTC",
                "servers": ["1.2.3.4", "de.ntp.pool.org"]
            },
            "interfaces": [{
                "name": "eth0",
                "mode": "auto",
                "address": "120.0.0.1/24",
                "dns": ["1.1.1.1"],
                "gateway": "120.0.0.255",
                "metric": 100,
                "routes": [{
                    "address": "121.0.0.1/24",
                    "gateway": "120.0.0.255",
                    "metric": 50
                }]
            }],
            "proxy": {
                "http": {
                    "host": "120.0.0.50:8080",
                    "username": "",
                    "password": ""
                },
                "https": {
                    "host": "120.0.0.50:8443",
                    "username": "",
                    "password": ""
                },
                "ftp": {
                    "host": "120.0.0.50:8021",
                    "username": "",
                    "password": ""
                }
            },
            "netFieldCloud": {
                "defaultMode": 0,
                "modeOptions": ["manual", "advanced", "zeroTouch"],
                "defaultInstance": 0,
                "instanceOptions": [{
                    "name": "Production",
                    "host": "api.netfield.io"
                }],
                "upstreamProtocol": "AMQPWS"
            },
            "users": [
                {
                    "name": "my_super_admin",
                    "mode": "add",
                    "shell": "/bin/zsh",
                    "additionalGroups": ["sudo", "docker"],
                    "password": "$6$tsTQ1XOmu23ctGtt$SFRKDyuVl01Hnls.oCripu5zXLrNJ1ZbkJ1s2NAJrEf6n7F099OWbVOfSIqUubSqeME1J9P8taJ/MM8zM3hDB0",
                    "forcePasswordChange": true
                },
                {
                    "name": "dont_need_user",
                    "mode" : "delete"
                },
                {   "name": "admin",
                    "mode" : "change",
                    "password": "$6$tsTQ1XOmu23ctGtt$SFRKDyuVl01Hnls.oCripu5zXLrNJ1ZbkJ1s2NAJrEf6n7F099OWbVOfSIqUubSqeME1J9P8taJ/MM8zM3hDB0",
                    "forcePasswordChange": true
                }
            ]
        }
    }
}
